### ISSUE TITLE
Improve UX to mitigate human error

### ISSUE THREAD

**Issue by hongee** [dailybruin/meow#56]
The UI is not very intuitive in helping users figure out which day posts are scheduled. Could add a huge "Today" / "Tomorrow" label on the page to make it super obvious, but other ideas welcome.

**Comment by brmi** [comment]
I added code for a better date and time picker on the branch desiree/datepicker. 
<img width="1680" alt="screen shot 2017-11-09 at 4 31 25 pm" src="https://user-images.githubusercontent.com/7662531/32639339-4e65ec2e-c578-11e7-98a1-7ed3346b262f.png">
<img width="1680" alt="screen shot 2017-11-09 at 4 31 31 pm" src="https://user-images.githubusercontent.com/7662531/32639341-50fa2c52-c578-11e7-8a6d-d7a5c57daf2f.png">
<img width="1680" alt="screen shot 2017-11-09 at 4 31 45 pm" src="https://user-images.githubusercontent.com/7662531/32639345-52efbd2e-c578-11e7-80b6-00040be0f0f3.png">
<img width="1680" alt="screen shot 2017-11-09 at 4 31 48 pm" src="https://user-images.githubusercontent.com/7662531/32639348-55a7c502-c578-11e7-9d5a-001e1325238b.png">
<img width="1680" alt="screen shot 2017-11-09 at 4 32 14 pm" src="https://user-images.githubusercontent.com/7662531/32639350-58742e38-c578-11e7-86d7-61a2a880be43.png">

**Comment by brmi** [comment]
And also for the dashboard page
<img width="1680" alt="screen shot 2017-11-09 at 6 04 36 pm" src="https://user-images.githubusercontent.com/7662531/32639377-88215d86-c578-11e7-8681-5571ab8d009f.png">
<img width="1680" alt="screen shot 2017-11-09 at 6 04 45 pm" src="https://user-images.githubusercontent.com/7662531/32639383-8c3e32a4-c578-11e7-9452-25348722ecc5.png">
<img width="1680" alt="screen shot 2017-11-09 at 6 04 53 pm" src="https://user-images.githubusercontent.com/7662531/32639388-920f5686-c578-11e7-965c-17c2e36d99e4.png">

Not sure to pull because I still get that error I mentioned earlier in Slack; however, this error was there before I changed any code. 
<img width="1014" alt="screen shot 2017-11-09 at 1 17 55 am" src="https://user-images.githubusercontent.com/7662531/32639403-a31d7156-c578-11e7-91be-398cac8cb41f.png">

**Comment by brmi** [comment]
Section Object -> Actual Section name
<img width="330" alt="screen shot 2017-11-29 at 6 16 10 pm" src="https://user-images.githubusercontent.com/7662531/33409663-6e08fc1a-d531-11e7-9ce1-5e4d83e857c7.png">

**Comment by brmi** [comment]
Added arrows for sorting columns
<img width="1008" alt="screen shot 2017-11-29 at 9 53 30 pm" src="https://user-images.githubusercontent.com/7662531/33416133-cb895b8c-d54f-11e7-86e3-356848277209.png">

**Comment by brmi** [comment]
Made the default time the current time when you make a new meow post - can be used as publish now feature?
<img width="1680" alt="screen shot 2017-12-01 at 8 11 47 pm" src="https://user-images.githubusercontent.com/7662531/33511685-11ad7a28-d6d4-11e7-98a1-dd202c6ed966.png">
